export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const CURRENT_CATEGORY = "CURRENT_CATEGORY";
export const SAVE_PRODUCTS = "SAVE_PRODUCTS";


